In [1]:
import numpy as np
import pandas as pd  
from sklearn.decomposition import PCA


In [2]:
df = pd.read_csv('churn_data.csv')

In [3]:
df.drop('CSA',axis=1,inplace = True) 

In [14]:
train = df[df['CALIBRAT']==1]
test = df[df['CALIBRAT']==0]
train.is_copy = False
test.is_copy = False

In [15]:
y_train = train['CHURNDEP']
y_train.is_copy = False

In [9]:
train.drop('CHURNDEP',axis =1,inplace = True)

In [10]:
X_train = train

In [11]:
X_train.is_copy

False

In [13]:
y_test = test['CHURNDEP']
y_test.is_copy = False

In [16]:
test.drop('CHURNDEP',axis =1,inplace = True)

In [17]:
X_test = test

In [19]:
X_test.is_copy

False

In [20]:
X_train.isnull().sum().sum()

2980

In [21]:
X_train.fillna(X_train.mean(),inplace=True)

ID     REVENUE          MOU  RECCHRGE  DIRECTAS      OVERAGE  \
31047  31048   38.000000     7.500000  38.00000  0.000000     0.000000   
31048  31049   55.230000   570.500000  71.98000  0.000000     0.000000   
31049  31050   38.052500   682.500000  52.49000  0.247500     0.000000   
31050  31051   97.337500  1039.000000  50.00000  4.950000   419.500000   
31051  31052   35.295000    24.250000  34.98000  0.000000     0.000000   
31052  31053   81.000000  1056.250000  75.00000  0.000000     0.000000   
31053  31054   63.017500   440.250000  59.98000  0.000000     5.750000   
31054  31055   29.990000    47.000000  29.99000  0.000000     0.000000   
31055  31056   21.150000    45.500000  16.99000  0.000000    14.000000   
31056  31057   30.000000   155.750000  30.00000  0.000000     0.000000   
31057  31058  145.795000  1293.250000  67.74500  0.000000   264.750000   
31058  31059   37.990000    71.000000  37.99000  0.000000     0.000000   
31059  31060   91.175000   332.750000  75.00000  0.000000     0.000000   
31060  31061   29.735000    65.250000  29.99000  0.990000     1.750000   
31061  31062   84.907500   745.000000  84.99000  0.495000     0.000000   
31062  31063   66.285000  1229.750000  59.99000  2.970000    52.750000   
31063  31064   93.020000  1348.250000  75.00000  0.000000     4.750000   
31064  31065   56.315000  1010.500000  59.99000  0.000000    10.250000   
31065  31066   72.810000  1306.000000  77.89750  0.000000     0.000000   
31066  31067  103.282500  1376.000000  84.99000  0.742500    38.000000   
31067  31068   71.857500   537.500000  75.00000  0.495000     0.000000   
31068  31069  114.132500  1649.750000  83.00000  1.732500    51.500000   
31069  31070   45.847500    69.500000  50.47750  0.000000     0.000000   
31070  31071  105.845000   784.000000  79.99000  0.247500     0.000000   
31071  31072   33.850000   225.000000  29.99000  0.247500     0.000000   
31072  31073   75.000000   342.750000  75.00000  0.000000     0.000000   
31073  31074   97.827500  1669.500000  83.00000  3.712500     0.000000   
31074  31075   55.505000   516.000000  50.00000  0.247500    29.750000   
31075  31076   70.190000   797.250000  60.00000  0.000000    43.250000   
31076  31077   18.000000    14.250000  15.00000  0.000000    12.000000   
...      ...         ...          ...       ...       ...          ...   
71017  71018   58.632643   513.973510  46.27196  0.878711    40.863133   
71018  71019   58.632643   513.973510  46.27196  0.878711    40.863133   
71019  71020   36.123333   158.666667  30.00000  0.990000    14.666667   
71020  71021   42.980000  1282.333333  44.99000  0.000000    22.333333   
71021  71022  534.930000  4719.000000  10.00000  6.930000  2018.000000   
71022  71023   29.990000    47.000000  29.99000  0.000000     0.000000   
71023  71024   45.490000   648.000000  44.99000  0.000000    30.000000   
71024  71025   58.632643   513.973510  46.27196  0.878711    40.863133   
71025  71026   36.640000    62.000000  32.49000  0.000000     3.000000   
71026  71027   58.632643   513.973510  46.27196  0.878711    40.863133   
71027  71028   32.323333   100.333333  29.99000  0.000000     6.666667   
71028  71029   58.632643   513.973510  46.27196  0.878711    40.863133   
71029  71030   58.632643   513.973510  46.27196  0.878711    40.863133   
71030  71031   58.632643   513.973510  46.27196  0.878711    40.863133   
71031  71032   58.632643   513.973510  46.27196  0.878711    40.863133   
71032  71033   58.632643   513.973510  46.27196  0.878711    40.863133   
71033  71034   24.990000     0.000000  24.99000  0.000000     0.000000   
71034  71035   29.990000    56.750000  29.99000  0.000000     0.000000   
71035  71036   57.670000   534.666667  44.99000  0.000000    64.000000   
71036  71037   58.632643   513.973510  46.27196  0.878711    40.863133   
71037  71038   30.237500    63.250000  29.99000  0.247500     0.000000   
71038  71039   58.632643   513.973510  46.27196  0.878711    40.863133   
71039  71040  

In [22]:
X_test.fillna(X_test.mean(),inplace=True)

ID     REVENUE          MOU    RECCHRGE   DIRECTAS      OVERAGE  \
0          1   57.492500   482.750000   37.425000   0.247500    22.750000   
1          2   82.275000  1312.250000   75.000000   1.237500     0.000000   
2          3   31.662500    25.500000   29.990000   0.247500     0.000000   
3          4   62.127500    97.500000   65.985000   2.475000     0.000000   
4          5   25.225000     2.500000   25.000000   0.000000     0.000000   
5          6  212.515000  1971.500000   84.990000   2.227500   249.500000   
6          7   42.565000   270.500000   37.480000   0.247500     6.000000   
7          8   35.590000   153.000000   29.990000   0.000000    16.000000   
8          9   55.270000  1212.750000   49.990000   0.742500     0.000000   
9         10   50.965000   162.000000   69.990000   0.000000     2.500000   
10        11   25.492500   299.500000   24.990000   0.000000     0.750000   
11        12   37.662500   971.750000   35.990000   0.247500     4.750000   
12        13   30.260000    34.500000   29.990000   0.000000     0.000000   
13        14   30.000000    94.000000   30.000000   0.000000     0.000000   
14        15   35.552500   138.750000   34.990000   0.247500     0.000000   
15        16   28.500000    65.750000   30.000000   0.000000     0.000000   
16        17   99.912500  1193.750000   75.000000   0.495000    97.250000   
17        18   82.162500   660.000000   50.000000   0.000000   100.750000   
18        19   30.000000    56.000000   30.000000   0.000000     0.000000   
19        20   20.180000     1.250000   20.000000   0.000000     0.000000   
20        21   42.885000   406.000000   40.000000   0.000000    53.750000   
21        22  342.857500  2961.250000  139.960000  11.137500  1444.750000   
22        23   54.960000   244.000000   51.990000   2.970000     0.000000   
23        24   17.427500    19.750000   16.990000   0.000000     1.250000   
24        25  107.250000  1671.000000   75.000000   0.000000   126.000000   
25        26  163.540000  1437.500000   82.950000   2.475000     0.000000   
26        27   21.120000    17.750000   18.870000   0.000000     9.000000   
27        28   76.737500  1007.750000   59.990000   0.495000    65.250000   
28        29  196.762500  3479.000000   85.000000   4.950000   872.250000   
29        30   55.190000  1087.750000   69.990000   0.000000    13.000000   
...      ...         ...          ...         ...        ...          ...   
31017  31018   86.380000   695.750000   49.990000   0.000000    88.000000   
31018  31019  181.387500   688.750000   22.492500   0.495000   414.750000   
31019  31020   10.487500   490.000000   10.000000   0.000000     1.250000   
31020  31021   93.037500   456.500000   69.990000   0.247500    82.000000   
31021  31022   98.472500  1620.750000   77.490000   5.692500    22.000000   
31022  31023   71.737500   382.250000   44.990000   3.465000    73.250000   
31023  31024   10.027500   146.000000    7.257500   0.247500     0.000000   
31024  31025   59.136135   540.856181   47.654057   0.913738    39.107286   
31025  31026  118.562500  3239.000000   99.990000   0.247500    29.500000   
31026  31027  116.452500   862.000000   44.990000   0.000000   202.500000   
31027  31028   44.990000    70.500000   54.990000   0.000000     0.000000   
31028  31029   74.455000   502.500000   44.990000   3.465000    80.000000   
31029  31030   43.272500   380.500000   40.087500   1.485000    23.000000   
31030  31031   50.282500   567.000000   59.990000   0.000000     0.500000   
31031  31032   75.635000     0.000000    0.000000   0.000000     0.000000   
31032  31033   38.732500   204.250000   49.990000   0.742500     0.000000   
31033  31034   39.127500   122.000000   24.990000   0.000000    66.250000   
31034  31035   12.990000     1.000000   10.000000   0.000000     0.000000   
31035  31036   73.065000   603.000000   39.187500   0.247500   142.750000   
31036  31037  130.315000  1072.250000   49.022500   0.000000   203.250000   
31037 

In [24]:
y_train.isnull().sum().sum() # NO NEED TO FILL SINCE NO NULL VALUES

0

In [25]:
#DATA IS READY AFTER IMPUTATION AND IT HAS BEEN DIVIDED INTO TWO PARTS ACCORDING TO CALIBRAT FEATURE


In [26]:
X_train.shape

(40000, 77)

In [27]:
#SINCE THERE ARE 77 FEATURES,DATA NEEDS TO BE CONSIDERED IN RELATIVELY LESS DIMENTIONS 
#HERE I HAVE USED PCA FOR DIMENTIONALITY REDUCTION.
#First i have splitted the training data further into  train_cal and test_cal

In [28]:
 from sklearn.model_selection import train_test_split 

In [29]:
X_train_cal, X_test_cal, y_train_cal, y_test_cal = train_test_split(X_train,y_train , test_size=0.25, random_state=0)

In [30]:
#PCA

In [31]:
pca = PCA(n_components = 30,whiten = True)

In [32]:
X_train_calP = pca.fit(X_train_cal).transform(X_train_cal)

In [33]:
X_test_calP = pca.fit(X_test_cal).transform(X_test_cal)

In [35]:
pca.explained_variance_ratio_

array([  8.93734370e-01,   1.05807001e-01,   3.08841297e-04,
         7.06890835e-05,   4.95387205e-05,   9.08393994e-06,
         6.50501699e-06,   4.26271430e-06,   2.71782805e-06,
         2.43869784e-06,   1.20454495e-06,   8.90352449e-07,
         6.42777302e-07,   6.24259931e-07,   4.27190206e-07,
         1.88996508e-07,   1.75556731e-07,   1.19406363e-07,
         1.07687251e-07,   5.73161031e-08,   3.53753811e-08,
         3.04465409e-08,   1.42044038e-08,   1.23361538e-08,
         6.28994648e-09,   5.23053882e-09,   3.20781321e-09,
         8.76395144e-10,   8.49343487e-10,   3.80036317e-10])

In [36]:
#Since most of the variance is in first two dimentions, n=2 will be selected

In [37]:
pca = PCA(n_components = 2,whiten = True)

In [38]:
X_train_calP = pca.fit(X_train_cal).transform(X_train_cal)
X_test_calP = pca.fit(X_test_cal).transform(X_test_cal)

In [39]:
pca.explained_variance_ratio_

array([ 0.89373437,  0.105807  ])

In [40]:
# Now the data is preprocessed and since PCA has inbuilt standardization,no need to normalize the data further.

In [41]:
#Logistic regression model on calibration data

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
lg = LogisticRegression(C=1e5)
lg.fit(X_train_calP,y_train_cal)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [46]:
y_pred_lg = lg.predict(X_test_calP)

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_cal, y_pred_lg)

In [48]:
print('confusion_matrix')
print(cm)

[[5014    0]
 [   0 4986]]


In [49]:
from sklearn.metrics import accuracy_score as ac

In [50]:
accuracy_logistic_calibration =ac(y_test_cal, y_pred_lg)

In [54]:
print('Accuracy')
print(accuracy_logistic_calibration)


Accuracy
1.0


In [102]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train_calP,y_train_cal)

y_pred_knn = knn.predict(X_test_calP)
cm_knn = confusion_matrix(y_test_cal, y_pred_knn)
accuracy_knn = ac(y_test_cal,y_pred_knn)
print('confusion_matrix')
print(cm_knn)
print('accuracy')
print(accuracy_knn)

confusion_matrix
[[5014    0]
 [   0 4986]]
accuracy
1.0


In [56]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_calP,y_train_cal)
y_pred_nb = nb.predict(X_test_calP)
cm_nb = confusion_matrix(y_test_cal, y_pred_nb)
accuracy_nb = ac(y_test_cal,y_pred_nb)
print('confusion_matrix')
print(cm_nb)
print('accuracy')
print(accuracy_nb)

[[5014    0]
 [   0 4986]]
accuracy
1.0


In [58]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt.fit(X_train_calP,y_train_cal)
y_pred_dt = dt.predict(X_test_calP)
cm_dt = confusion_matrix(y_test_cal, y_pred_dt)
accuracy_dt = ac(y_test_cal,y_pred_dt)
print('confusion_matrix')
print(cm_dt)
print('accuracy')
print(accuracy_dt)

[[5014    0]
 [   0 4986]]
accuracy
1.0


In [60]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf.fit(X_train_calP,y_train_cal)
y_pred_rf = rf.predict(X_test_calP)
cm_rf = confusion_matrix(y_test_cal, y_pred_rf)
accuracy_rf = ac(y_test_cal,y_pred_rf)
print('confusion_matrix')
print(cm_rf)
print('accuracy')
print(accuracy_rf)

[[5014    0]
 [   0 4986]]
accuracy
1.0


In [63]:
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf', random_state = 0)
svc.fit(X_train_calP, y_train_cal)
y_pred_svm = svc.predict(X_test_calP)
cm_svm = confusion_matrix(y_test_cal,y_pred_svm)
accuracy_svm = ac(y_test_cal,y_pred_svm)
print('confusion_matrix')
print(cm_svm)
print('accuracy')
print(accuracy_svm)

[[5014    0]
 [   0 4986]]
accuracy
1.0


In [64]:
print('Fitting for Validation data')

Fitting for Validation data


In [65]:
x_train = pca.fit(X_train).transform(X_train)
x_test = pca.fit(X_test).transform(X_test)

In [66]:
pca.explained_variance_ratio_

array([ 0.99361565,  0.00589515])

In [101]:
#Logistic_Regression
lg_validation = LogisticRegression(C=1e5)
lg_validation.fit(x_train,y_train)
y_pred_lg_validation = lg_validation.predict(x_test)

#just to cheak how much variation is there with previous fit ##
y_pred_lg = lg.predict(x_test)
cm_lg_out = confusion_matrix(y_pred_lg_validation,y_pred_lg)
cm_lg_out


array([[ 3676,     0],
       [    2, 27369]], dtype=int64)

In [95]:
y_pred_lg_validation.shape 

(31047,)

In [71]:
y_pred_lg.mean()

0.88153444777273171

In [72]:
y_train.mean()

0.5

In [96]:
output = pd.DataFrame({'churndep':y_pred_lg_validation.tolist()})
output.to_csv('output_logistic.csv')

In [103]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn_validation = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_validation.fit(x_train,y_train)
y_pred_knn_validation = knn_validation.predict(x_test)

In [104]:
output = pd.DataFrame({'churndep':y_pred_knn_validation.tolist()})
output.to_csv('output_Knn.csv')

In [99]:
#just to cheak how much variation is there with previous fit ##
y_pred_knn = knn.predict(x_test)
cm_knn_out = confusion_matrix(y_pred_knn_validation,y_pred_knn)
cm_knn_out

array([[ 3676,     0],
       [    2, 27369]], dtype=int64)

In [77]:
#GaussianNB
nb_validation = GaussianNB()
nb_validation.fit(x_train,y_train)
y_pred_nb_validation = nb_validation.predict(x_test)

In [100]:
output = pd.DataFrame({'churndep':y_pred_nb_validation.tolist()})
output.to_csv('output_GaussianNB_classifier.csv')

In [81]:
#just to cheak how much variation is there with previous fit ##
y_pred_nb = nb.predict(x_test)
accuracy_out = ac(y_pred_nb_validation,y_pred_nb)


1.0

In [83]:
#Decision_Tree
dt_validation = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt_validation.fit(x_train,y_train)
y_pred_dt_validation = dt_validation.predict(x_test)

In [84]:
output = pd.DataFrame({'churndep':y_pred_dt_validation.tolist()})
output.to_csv('output_decision_tree.csv')

In [87]:
#just to cheak how much variation is there with previous fit ##
y_pred_dt = dt.predict(x_test)
cm_dt = confusion_matrix(y_pred_dt_validation, y_pred_dt)
accuracy_dt = ac(y_pred_dt_validation,y_pred_dt)
accuracy_dt

[[ 3371    11]
 [    0 27665]]


0.99964569845717788

In [88]:
#Random_forest
rf_validation = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf_validation.fit(x_train,y_train)
y_pred_rf_validation = rf_validation.predict(x_test)

In [89]:
output = pd.DataFrame({'churndep':y_pred_rf_validation.tolist()})
output.to_csv('output_random_forest.csv')

In [90]:
y_pred_rf = rf.predict(x_test)
cm_rf = confusion_matrix(y_pred_rf_validation, y_pred_rf)
accuracy_rf = ac(y_pred_rf_validation,y_pred_rf)
accuracy_rf

[[ 3371    11]
 [    0 27665]]


0.99964569845717788

In [91]:
#Support_Vector_Machine
from sklearn.svm import SVC
svc_validation = SVC(kernel = 'rbf', random_state = 0)
svc_validation.fit(x_train,y_train)
y_pred_svc_validation = svc_validation.predict(x_test)

In [92]:
output = pd.DataFrame({'predicted_by_SVM_churndep':y_pred_svc_validation.tolist()})
output.to_csv('output_SVM.csv')

In [93]:
y_pred_svc = svc.predict(x_test)
cm_svc = confusion_matrix(y_pred_svc_validation, y_pred_svc)
accuracy_svc = ac(y_pred_svc_validation,y_pred_svc)
accuracy_svc

[[ 3694     0]
 [    2 27351]]


0.99993558153766871